export const BASE_API_URL = 'http://api2.gateway.dev:9000';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';

export const GET_PLUGINS = 'GET_PLUGINS';
export const UPDATE_PLUGIN = 'UPDATE_PLUGIN';

export const GET_USERS = 'GET_USERS';

export const GET_MICROSERVICES = 'GET_MICROSERVICES';

export const GET_ENDPOINTS = 'GET_ENDPOINTS';

export const GET_STADISTICS = 'GET_STADISTICS';
export const GET_TIME_BY_REQUEST_STADISTICS = 'GET_TIME_BY_REQUEST_STADISTICS';

export const LOGIN = 'LOGIN';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const GENERATE_TOKEN = 'GENERATE_TOKEN';
export const LOGOUT = 'LOGOUT';
